name: CI Workflow
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
          mongodb-replica-set: test-rs
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: build --info
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_ADMIN_TOKEN }}
      - name: Build Container Image
        if: contains(github.ref, 'refs/heads/main')
        uses: gradle/gradle-build-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_ADMIN_TOKEN }}
          GCR_SECRET: ${{ secrets.ORG_GCR_ADMIN_JSON }}
        with:
          arguments: bootBuildImage --publishImage --pullPolicy=IF_NOT_PRESENT
      - name: Update Helm Values
        if: contains(github.ref, 'refs/heads/main')
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: updateHelmValues
      - uses: EndBug/add-and-commit@v7.5.0
        if: contains(github.ref, 'refs/heads/main')
        with:
          message: 'Update deployment/values.test.yaml to trigger ARGO CD sync'
          default_author: github_actions
