name: Java Gradle Release Service Workflow
on:
  workflow_call:
    inputs:
      versionIncrement:
        type: string
        description: The version incrementer
        required: true
        default: incrementPatch
jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/main')
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_ADMIN_TOKEN }}
      GCR_SECRET: ${{ secrets.ORG_GCR_ADMIN_JSON }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Release
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: createRelease -Prelease.versionIncrementer=${{ inputs.versionIncrement }}

      - name: Build Container Image
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: assemble bootBuildImage --publishImage --pullPolicy=IF_NOT_PRESENT

      - name: Push Release
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: pushRelease -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ github.token }}

